apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app:latest  # Change if using a remote repository
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-service:5432/mydatabase"
