kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000      # The port inside the cluster
      targetPort: 5000  # The port exposed by your container
  type: ClusterIP  # Use LoadBalancer if exposing externally
